"use strict";
exports.__esModule = true;
var express = require("express");
var logger = require("morgan");
var registerRouter = require("./routes/user/registerUser");
var loginRouter = require("./routes/user/loginUser");
var getStatsRouter = require('./routes/user/stats/getStats');
var putStatsRouter = require('./routes/user/stats/putStats');
var usersRouter = require('./routes/users');
var server = express();
var port = process.env.PORT || 3000;
server.use(logger('dev'));
server.use(express.json());
server.use(express.urlencoded({ extended: true }));
server.use('/api/users', usersRouter);
server.use('/api/user/login', loginRouter);
server.use('/api/user/register', registerRouter);
server.use('/api/user/stats/get', getStatsRouter);
server.use('/api/user/stats/put', putStatsRouter);
server.listen(port, function () {
    console.log('Example server listening on port ' + port + '!');
});
